# This file defines build-time configuration. There should be no references to env vars in here
# unless they're REALLY compile-time - which they're usually not as explained here:
#
#   https://12factor.net/config
#
# It is no longer generated by `mix new` but may be added to leverage app env configuration
# only when REALLY needed - either case of an app or a truly global config in lib. More info:
#
#   https://hexdocs.pm/elixir/master/library-guidelines.html#avoid-application-configuration)

# Replaces `use Mix.Config` for native dependency-free configuration
import Config

# Configure mix-oriented dev/test envs & build-time/default config for prod env
config :configurable,
  message: "Test message",
  color: :cyan,
  interval: 1_000,
  start_printer: Mix.env() != :test

# Same for library config
config :logger,
  level: :info,
  console: [metadata: :all]
